name: Makefile

on:
  push:
  pull_request:

permissions:
  security-events: write
  actions: read
  contents: read

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make:
    name: make
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - make: build
            docker: false
          - make: test
            docker: false
          - make: race
            docker: false
          - make: docker-build
            docker: true
          - make: e2e-test
            docker: true
          - make: goreleaser
            docker: false
          - make: lint
            docker: false

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: matrix.docker == true

      - name: make ${{ matrix.make }}
        run: make ${{ matrix.make }}
        if: matrix.make != 'goreleaser'  
        env:
          GO_SKIP_GENERATE: 1

      - name: Upload results to codecov
        uses: codecov/codecov-action@v3
        if: matrix.make == 'test'

      - name: Check GoReleaser configuration
        uses: goreleaser/goreleaser-action@v4
        if: matrix.make == 'goreleaser' 
        with:
          args: check
